/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rojarna.projektrojarna;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Oskar
 */
public class CampaignView extends javax.swing.JPanel implements PropertyChangeListener,Observer{
    
    private CampaignModel model;
    GameBoardView board;

    /**
     * Creates new form ModelView
     */
    public CampaignView(CampaignModel model) {
        initComponents();
        this.model=model;
        model.addObserver(this);
        GameBoardView board = new GameBoardView(model, this);
        boardPanel.add(board);
        this.board=board;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        lifePanel = new javax.swing.JPanel();
        lifeLabel1 = new javax.swing.JLabel();
        lifeLabel2 = new javax.swing.JLabel();
        lifeLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mineLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        PU1 = new javax.swing.JToggleButton();
        PU2 = new javax.swing.JToggleButton();
        PU3 = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        pausButton = new javax.swing.JToggleButton();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        boardPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuPanel.setMinimumSize(new java.awt.Dimension(200, 408));
        menuPanel.setPreferredSize(new java.awt.Dimension(200, 408));
        menuPanel.setLayout(new java.awt.GridLayout(8, 1));

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        timeLabel.setText("Time");
        jPanel3.add(timeLabel);

        menuPanel.add(jPanel3);

        levelLabel.setText("Level");
        jPanel4.add(levelLabel);

        menuPanel.add(jPanel4);

        lifeLabel1.setText("LifeIcon");
        lifePanel.add(lifeLabel1);

        lifeLabel2.setText("LifeIcon");
        lifePanel.add(lifeLabel2);

        lifeLabel3.setText("LifeIcon");
        lifePanel.add(lifeLabel3);

        menuPanel.add(lifePanel);

        jLabel6.setText("MineIcon");
        jPanel6.add(jLabel6);

        mineLabel.setText("nbrOfMines");
        jPanel6.add(mineLabel);

        menuPanel.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        PU1.setText("PU1");
        PU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU1ActionPerformed(evt);
            }
        });
        jPanel7.add(PU1, new java.awt.GridBagConstraints());

        PU2.setText("PU2");
        PU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU2ActionPerformed(evt);
            }
        });
        jPanel7.add(PU2, new java.awt.GridBagConstraints());

        PU3.setText("PU3");
        PU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU3ActionPerformed(evt);
            }
        });
        jPanel7.add(PU3, new java.awt.GridBagConstraints());

        menuPanel.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel8);

        pausButton.setText("Paus");
        pausButton.setPreferredSize(new java.awt.Dimension(80, 35));
        pausButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausButtonActionPerformed(evt);
            }
        });
        jPanel9.add(pausButton);

        menuPanel.add(jPanel9);

        jButton2.setText("Avsluta");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel10.add(jButton2);

        menuPanel.add(jPanel10);

        add(menuPanel, java.awt.BorderLayout.WEST);

        boardPanel.setMinimumSize(new java.awt.Dimension(100, 408));
        boardPanel.setPreferredSize(new java.awt.Dimension(200, 408));
        add(boardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void PU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU1ActionPerformed
        if(PU3.isSelected()){
            PU3.setSelected(false);
        }
    }//GEN-LAST:event_PU1ActionPerformed

    private void PU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU2ActionPerformed
        model.usePowerup(new PUShowAll(),0,0);
        PU2.setSelected(false);
    }//GEN-LAST:event_PU2ActionPerformed

    private void PU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU3ActionPerformed
        if(PU1.isSelected()){
            PU1.setSelected(false);
        }
    }//GEN-LAST:event_PU3ActionPerformed

    private void pausButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausButtonActionPerformed
        model.pauseGame(pausButton.isSelected());
    }//GEN-LAST:event_pausButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton PU1;
    private javax.swing.JToggleButton PU2;
    private javax.swing.JToggleButton PU3;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel lifeLabel1;
    private javax.swing.JLabel lifeLabel2;
    private javax.swing.JLabel lifeLabel3;
    private javax.swing.JPanel lifePanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel mineLabel;
    private javax.swing.JToggleButton pausButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    public void propertyChange(PropertyChangeEvent evt) {
        String command = evt.getPropertyName();
        labelUpdate();
        if(command.equals("leftClick")){
            SquareView view = (SquareView)evt.getNewValue();
            if(PU1.isSelected()){
                model.usePowerup(new PUSafeChooseArea(),view.getXPos(), view.getYPos());
                PU1.setSelected(false);
            }else if(PU3.isSelected()){
                //Kod för sista PU.
                PU3.setSelected(false);
            }else{
            model.chooseSquare(view.getXPos(), view.getYPos());                
            }
            
        }else if(command.equals("rightClick")){
            PU1.setSelected(false);
            PU3.setSelected(false);
            SquareView view = (SquareView)evt.getNewValue();
            model.markSquare(view.getXPos(), view.getYPos());
        }
    }

    public void update(Observable o, Object arg) {
        if(model.isGameOver()){
            
        }
        if(model.isLvlComplete()){
            JOptionPane.showConfirmDialog(null,
            "Play next level?", "Play next level?", JOptionPane.YES_NO_OPTION);
            model.nextLevel();
            board.renewBoard(this);
        }
        labelUpdate();
    }
    
    private void labelUpdate(){
        timeLabel.setText(model.getGameTime()+"");
        levelLabel.setText("Level: "+model.getLevel());
        setLives(model.getLives());
        mineLabel.setText("NA");
    }
    
    private void setLives(int lives){
        if(lives>0){
            lifeLabel1.setIcon(new ImageIcon("src/resources/heart.png"));
            
            if(lives>1){
                lifeLabel2.setIcon(new ImageIcon("src/resources/heart.png"));
                
                if(lives>2){
                    lifeLabel3.setIcon(new ImageIcon("src/resources/heart.png"));
                }else{
                    lifeLabel3.setIcon(null);
                }
            }else{
                lifeLabel2.setIcon(null);
            }
        }else{
            lifeLabel1.setIcon(null);
        }
    }
}
