/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rojarna.projektrojarna;

import java.awt.GridLayout;

/**
 *
 * @author Tom
 */
public class GameBoardView extends javax.swing.JPanel {
    /**
     * Creates new form GameBoardView
     */
    public GameBoardView() {
        initComponents();
        setLayout(new GridLayout(10,10));
        int x=0;
        int y=0;
        for(int i=0;i<100;i++){
            add(new SquareView(x,y));
            x++;
            if(x==10){
                x=0;
                y++;
            }
        }
    }
    
    public GameBoardView(int x, int y){
        initComponents();
        setLayout(new GridLayout(x,y));
        int posx=0;
        int posy=0;
        for(int i=0;i<x*y;i++){
            add(new SquareView(posx,posy));
            posx++;
            if(posx==x){
                posx=0;
                posy++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
