/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rojarna.projektrojarna;

import java.beans.PropertyChangeListener;

/**
 *
 * @author Tom
 */
public class GameBoardView extends javax.swing.JPanel{
    /**
     * Creates new form GameBoardView
     */
    
    private AbstractGameModel model;
    
    public GameBoardView(AbstractGameModel model,ModelView view) {
        initComponents();
        
        this.model = model;
        setBoard(view);
    }
    
    public void renewBoard(ModelView view){
        this.removeAll();
        setBoard(view);
    }
    
    private void setBoard(ModelView view){
        setLayout(new java.awt.GridLayout(model.getWidth(),model.getHeight()));
        
        for(int x=0;x<model.getWidth();x++){
            for(int y=0;y<model.getHeight();y++){
                SquareView s = new SquareView(x,y);
                model.addObserver(s);
                s.addPropertyChangeListener(view);
                add(s);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
