/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rojarna.projektrojarna;

/**
 *
 * @author Gaming
 */
public class MenuPanel extends javax.swing.JPanel {

    //PropertyChangeSupport pcs = new PropertyChangeSupport(this);
    
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
        
        jLabel1.setAlignmentX(CENTER_ALIGNMENT);
        ClassicButton.setAlignmentX(CENTER_ALIGNMENT);
        CampaignButton.setAlignmentX(CENTER_ALIGNMENT);
        ExitButton.setAlignmentX(CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        ButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 35), new java.awt.Dimension(0, 35), new java.awt.Dimension(0, 35));
        ClassicButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        CampaignButton = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        ExitButton = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler1);

        ButtonPanel.setLayout(new javax.swing.BoxLayout(ButtonPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Röj");
        ButtonPanel.add(jLabel1);
        ButtonPanel.add(filler2);

        ClassicButton.setText("New Classic Game");
        ClassicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassicButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(ClassicButton);
        ButtonPanel.add(filler4);

        CampaignButton.setText("New Campaign Game");
        CampaignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampaignButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(CampaignButton);
        ButtonPanel.add(filler5);

        ExitButton.setText("Exit Program");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(ExitButton);

        add(ButtonPanel);
        add(filler3);
    }// </editor-fold>//GEN-END:initComponents

    private void ClassicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassicButtonActionPerformed
        this.firePropertyChange("ClassicGame", null, this);
    }//GEN-LAST:event_ClassicButtonActionPerformed

    private void CampaignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampaignButtonActionPerformed
        this.firePropertyChange("CampaignGame", null, this);
    }//GEN-LAST:event_CampaignButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.firePropertyChange("ExitGame", null, this);
    }//GEN-LAST:event_ExitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton CampaignButton;
    private javax.swing.JButton ClassicButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}