/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rojarna.projektrojarna;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author Oskar
 */
public class ModelView extends javax.swing.JPanel implements PropertyChangeListener,Observer{
    
    private CampaignModel model;
    GameBoardView board;

    /**
     * Creates new form ModelView
     */
    public ModelView(CampaignModel model) {
        initComponents();
        this.model=model;
        model.addObserver(this);
        GameBoardView board = new GameBoardView(model, this);
        boardPanel.add(board);
        this.board=board;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        PU1 = new javax.swing.JToggleButton();
        PU2 = new javax.swing.JToggleButton();
        PU3 = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        boardPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 408));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 408));
        jPanel2.setLayout(new java.awt.GridLayout(8, 1));

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        timeLabel.setText("Time");
        jPanel3.add(timeLabel);

        jPanel2.add(jPanel3);

        jLabel2.setText("Level");
        jPanel4.add(jLabel2);

        jPanel2.add(jPanel4);

        jLabel3.setText("LifeIcon");
        jPanel5.add(jLabel3);

        jLabel4.setText("LifeIcon");
        jPanel5.add(jLabel4);

        jLabel5.setText("LifeIcon");
        jPanel5.add(jLabel5);

        jPanel2.add(jPanel5);

        jLabel6.setText("MineIcon");
        jPanel6.add(jLabel6);

        jLabel7.setText("nbrOfMines");
        jPanel6.add(jLabel7);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        PU1.setText("PU1");
        PU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU1ActionPerformed(evt);
            }
        });
        jPanel7.add(PU1, new java.awt.GridBagConstraints());

        PU2.setText("PU2");
        PU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU2ActionPerformed(evt);
            }
        });
        jPanel7.add(PU2, new java.awt.GridBagConstraints());

        PU3.setText("PU3");
        PU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU3ActionPerformed(evt);
            }
        });
        jPanel7.add(PU3, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        jButton1.setText("Paus");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel9.add(jButton1);

        jPanel2.add(jPanel9);

        jButton2.setText("Absluta");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel10.add(jButton2);

        jPanel2.add(jPanel10);

        add(jPanel2, java.awt.BorderLayout.WEST);

        boardPanel.setMinimumSize(new java.awt.Dimension(100, 408));
        boardPanel.setPreferredSize(new java.awt.Dimension(200, 408));
        add(boardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void PU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU1ActionPerformed
        if(PU3.isSelected()){
            PU3.setSelected(false);
        }
    }//GEN-LAST:event_PU1ActionPerformed

    private void PU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU2ActionPerformed
        model.usePowerup(new PUShowAll(),0,0);
        PU2.setSelected(false);
    }//GEN-LAST:event_PU2ActionPerformed

    private void PU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU3ActionPerformed
        if(PU1.isSelected()){
            PU1.setSelected(false);
        }
    }//GEN-LAST:event_PU3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton PU1;
    private javax.swing.JToggleButton PU2;
    private javax.swing.JToggleButton PU3;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    public void propertyChange(PropertyChangeEvent evt) {
        String command = evt.getPropertyName();
        if(command.equals("leftClick")){
            SquareView view = (SquareView)evt.getNewValue();
            if(PU1.isSelected()){
                model.usePowerup(new PUSafeChooseArea(),view.getXPos(), view.getYPos());
                PU1.setSelected(false);
            }else if(PU3.isSelected()){
                //Kod för sista PU.
                PU3.setSelected(false);
            }else{
            model.chooseSquare(view.getXPos(), view.getYPos());                
            }
        }else if(command.equals("rightClick")){
            PU1.setSelected(false);
            PU3.setSelected(false);
            SquareView view = (SquareView)evt.getNewValue();
            model.markSquare(view.getXPos(), view.getYPos());
        }
    }

    public void update(Observable o, Object arg) {
        if(model.isLvlComplete()){
            JOptionPane.showConfirmDialog(null,
            "Play next level?", "Play next level?", JOptionPane.YES_NO_OPTION);
            model.nextLevel();
            board.renewBoard(this);
        }
        timeLabel.setText(model.getTime()+"");
    }
}
