/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rojarna.projektrojarna;

import javax.swing.SwingUtilities;


/**
 *
 * @author Tom
 */
public class SquareView extends javax.swing.JPanel{
    private int x;
    private int y;
    
    /**
     * Creates new form SquareView
     */
    public SquareView(int x, int y) {
        initComponents();
    }
    
    public void setMark(String s){ // TODO the input chould late be an Icon
        Button.setText(s);
    }
    
    public void Pressed(String s){ // TODO also an Icon
        Button.setEnabled(false);
        Button.setText(s);
    }
    
    public int getBoardX(){
        return x;
    }
    public int getBoardY(){
        return y;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(20, 20));
        setMinimumSize(new java.awt.Dimension(20, 20));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(20, 20));

        Button.setText("jButton1");
        Button.setMaximumSize(new java.awt.Dimension(20, 20));
        Button.setMinimumSize(new java.awt.Dimension(20, 20));
        Button.setPreferredSize(new java.awt.Dimension(20, 20));
        Button.setSelected(true);
        Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMouseClicked
        if(SwingUtilities.isLeftMouseButton(evt)){
            //send
        }else if(SwingUtilities.isRightMouseButton(evt)){
            //send
        }
        else{
            // do nothing.
        }
    }//GEN-LAST:event_ButtonMouseClicked
                                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    // End of variables declaration//GEN-END:variables

}
